"""On-device export contracts (Core ML path reserved / optional on macOS)."""

from __future__ import annotations

from golfmate_algo.export.commercial_report import (
    CONTRACT_VERSION as COMMERCIAL_REPORT_VERSION,
    INFERENCE_METRIC_NAMES,
    PERSONAL_BASELINE_VERSION,
    PRACTICE_LOOP_FIELD_NAMES,
    PRACTICE_LOOP_VERSION,
    STRATEGY_FIELD_NAMES,
    STRATEGY_VERSION,
    TRUTH_METRIC_NAMES,
    CommercialSwingReport,
    PersonalBaselineSection,
    PracticeLoopSection,
    StrategySection,
    build_commercial_report,
    export_commercial_report,
    load_commercial_schema,
    validate_commercial_report_dict,
)
from golfmate_algo.export.edge_trajectory_contract import (
    CONTRACT_VERSION as EDGE_TRAJECTORY_CONTRACT_VERSION,
    INPUT_FS_HZ as EDGE_INPUT_FS_HZ,
    OUTPUT_DIM as EDGE_OUTPUT_DIM,
    TRAJECTORY_POINTS,
    EdgeTrajectoryOutput,
    load_edge_trajectory_schema,
    sample_trajectory_xyz,
)
from golfmate_algo.export.edge_trajectory_model import (
    EdgeTrajectoryStudent,
    extract_edge_features,
    fit_edge_student,
    load_edge_student,
    teacher_edge_output,
    train_default_edge_student,
)
from golfmate_algo.export.feature_contract import (
    CONTRACT_VERSION,
    FEATURE_NAMES,
    SwingFeatureVector,
    export_feature_vector,
    load_schema,
)

__all__ = [
    "COMMERCIAL_REPORT_VERSION",
    "CONTRACT_VERSION",
    "EDGE_INPUT_FS_HZ",
    "EDGE_OUTPUT_DIM",
    "EDGE_TRAJECTORY_CONTRACT_VERSION",
    "FEATURE_NAMES",
    "INFERENCE_METRIC_NAMES",
    "PERSONAL_BASELINE_VERSION",
    "PRACTICE_LOOP_FIELD_NAMES",
    "PRACTICE_LOOP_VERSION",
    "STRATEGY_FIELD_NAMES",
    "STRATEGY_VERSION",
    "TRUTH_METRIC_NAMES",
    "CommercialSwingReport",
    "EdgeTrajectoryOutput",
    "EdgeTrajectoryStudent",
    "PersonalBaselineSection",
    "PracticeLoopSection",
    "StrategySection",
    "SwingFeatureVector",
    "TRAJECTORY_POINTS",
    "build_commercial_report",
    "export_commercial_report",
    "export_feature_vector",
    "extract_edge_features",
    "fit_edge_student",
    "load_commercial_schema",
    "load_edge_student",
    "load_edge_trajectory_schema",
    "load_schema",
    "sample_trajectory_xyz",
    "teacher_edge_output",
    "train_default_edge_student",
    "validate_commercial_report_dict",
]
